### PR TITLE
Fix audio example being too complex

### PR DESCRIPTION
**Pull request by paked**
The previous audio example contained animation and movement.

IMO all examples should be their own little feature, and not combine the two together (Unless they are a sample game, like pong).

### CODE REVIEW

**Comment by paked** [comment]
Maybe it would be beneficial to have both examples?

**Comment by EtienneBruines** [comment]
Perhaps it should also show that audio can be "background audio", and "not background audio"? 

The reason it allowed for scrolling, is because the more you zoom out, the less you hear the weird man, but the bird stay the same.

**Comment by paked** [comment]
@EtienneBruines Ah. I see your point. I'll add those back in, but not the animation or movement.

**Comment by EtienneBruines** [comment]
:+1:

**Comment by matiwinnetou** [comment]
+1 on complexity. Such combo things we could demo in an example game but those small demos should help in writing tutorials.

**Comment by paked** [comment]
@EtienneBruines I think we should keep this example as it is. But have a second example with what you previously mentioned.

I'll do this in a separate PR.

Merge when ready.

**Pull request merged**
