### PR TITLE
Added AudioSystem / Changed to CameraSystem

### PR DESCRIPTION
**Pull request by EtienneBruines**
AudioSystem:
* First attempt with audio and OpenAL.
* Also works 3d-ish, including distance.
* We have to convert Stereo16 to Mono16, because only
mono sounds are affected by ditance.

CameraSystem:
* Updated Camera to CameraSystem

General:
* Changed all demos, so they won't be affected

Note: this is initial support for Audio; lots of improvements to be made, but it's nice to have something.

### CODE REVIEW

**Comment by paked** [comment]
Awesome contribution @EtienneBruines!

**Comment by EtienneBruines** [comment]
Still have to force-push some changes, so don't push just yet, but I'm waiting for that so I won't break comments (not sure if it would, but would be a shame if it did).

**Comment by EtienneBruines** [comment]
Everything is now according to the changes discussed. 

One thing I didn't address, is the `Playing` `State` w.r.t. the GoF. This is mostly because I'm not sure what I should be changing. 

It looks good to me, but as this is my PR, someone else should say/approve it :-).

**Comment by paked** [comment]
So, I'd be happy to have GoF in another PR.

**Comment by matiwinnetou** [comment]
GoF State pattern could be an overkill. One would have to play and check if this is not over engineered for a simple use case.

**Comment by paked** [comment]
@matiwinnetou does this LGTY?

**Comment by matiwinnetou** [comment]
yes, LGTM

**Comment by paked** [comment]
Thanks again @EtienneBruines!

**Pull request merged**
