### PR TITLE
Benchmark

### PR DESCRIPTION
**Pull request by EtienneBruines**
Added some benchmarks (not all of which are as useful), to benchmark certain `System`s.

Please review @matiwinnetou @paked, as I did some refactoring of the `Open` and `run` functions, which possibly could be done in a better manner. 

Some output:
```
➜  engi git:(benchmark) go test -bench .                                     
PASS
BenchmarkEmpty-8              	10000000	       116 ns/op
BenchmarkSystem10-8           	 5000000	       309 ns/op
BenchmarkSystem1000-8         	  100000	     17569 ns/op
BenchmarkEntity10-8           	10000000	       179 ns/op
BenchmarkEntity1000-8         	  300000	      3961 ns/op
BenchmarkCollisionSystem10-8  	   50000	     39614 ns/op
BenchmarkCollisionSystem100-8 	     500	   4015496 ns/op
BenchmarkCollisionSystem1000-8	       3	 446231737 ns/op
ok  	github.com/paked/engi	15.830s
```

This also allows for some profiling:

```
      flat  flat%   sum%        cum   cum%
    1560ms 16.27% 16.27%     2050ms 21.38%  runtime.mallocgc
    1080ms 11.26% 27.53%     2190ms 22.84%  runtime.mapaccess2
     820ms  8.55% 36.08%     8110ms 84.57%  github.com/paked/engi.(*CollisionSystem).Update
     670ms  6.99% 43.07%     4730ms 49.32%  github.com/paked/engi.(*Entity).GetComponent
     530ms  5.53% 48.59%      530ms  5.53%  reflect.ValueOf
     400ms  4.17% 52.76%      400ms  4.17%  runtime.aeshash64
     400ms  4.17% 56.93%      800ms  8.34%  runtime.interhash
     350ms  3.65% 60.58%      350ms  3.65%  runtime.mSpan_Sweep.func1
     340ms  3.55% 64.13%      340ms  3.55%  reflect.Value.Elem
     210ms  2.19% 66.32%     2260ms 23.57%  runtime.newobject
     190ms  1.98% 68.30%      670ms  6.99%  reflect.Value.Set
     190ms  1.98% 70.28%      280ms  2.92%  reflect.Value.assignTo
     180ms  1.88% 72.16%      180ms  1.88%  runtime.ifaceeq
     160ms  1.67% 73.83%      160ms  1.67%  reflect.Value.Type
     150ms  1.56% 75.39%      500ms  5.21%  runtime.heapBitsSweepSpan
     140ms  1.46% 76.85%      140ms  1.46%  runtime.xchg
     130ms  1.36% 78.21%      130ms  1.36%  runtime.futex
     130ms  1.36% 79.56%      310ms  3.23%  runtime.interequal
     130ms  1.36% 80.92%      130ms  1.36%  runtime.prefetchnta
     110ms  1.15% 82.06%      170ms  1.77%  runtime.convI2E
```

### CODE REVIEW

**Comment by paked** [comment]
reminder @paked to review this later.

**Comment by paked** [comment]
@EtienneBruines I honestly didn't know this was a thing, It doesn't seem that idiomatic... Means that a package is actually two packages, I'd prefer the so-called "whitebox testing" method.

**Comment by EtienneBruines** [comment]
Not sure if I could rebase this; with all the merges it's a bit tricky.

**Comment by paked** [comment]
@EtienneBruines Don't worry about it.

LGTM.

**Comment by EtienneBruines** [comment]
It LGTY, so let's merge.

**Pull request merged**
