### PR TITLE
Created headless mode

### PR DESCRIPTION
**Pull request by EtienneBruines**
Should be halfway for #40.

One can now choose to run (hopefully the same) code in
headless mode; no `GLFW` calls will be made.

`System`s can now also be set to `SkipOnHeadless`, so these `System`s
will get skipped all together.

Added headless-pong demo to see it in action.

### CODE REVIEW

**Comment by matiwinnetou** [comment]
This is for testing I guess?

**Comment by EtienneBruines** [comment]
Mostly testing/benchmarking, yes

**Comment by paked** [comment]
SO COOL!

**Comment by paked** [comment]
Thanks for the contribution!

**Pull request merged**
