### PR TITLE
Refactored Responder to CustomGame

### PR DESCRIPTION
**Pull request by EtienneBruines**
This means all mouse movement is now saved in the Mouse variable.
(not yet tested for "drag" movement)

Updated all examples to reflect changes.

Please review @paked @matiwinnetou because it has quite some changes. 

This is ~~almost~~ done; ~~only need to fix the `Scroll` behavior.~~

### CODE REVIEW

**Comment by EtienneBruines** [comment]
Fixed the `Scroll` behavior.

**Comment by paked** [comment]
LGTM

**Comment by matiwinnetou** [comment]
I think this needs to be rebased.

**Comment by paked** [comment]
Update to master. Then lets merge

**Comment by EtienneBruines** [comment]
Couldn't do this last commit in a separate PR (because it relied heavily on this branch). 

Please review, so we can merge this (so I can actually use the branches I created, together :smile: )

**Comment by matiwinnetou** [comment]
@EtienneBruines can your rebase those commits? At the end to have one commit?

**Comment by paked** [comment]
@EtienneBruines @matiwinnetou I'm not going to worry about rebasing on this one, is it good to go?

**Comment by paked** [comment]
@EtienneBruines I have tried to merge this locally, but I got a bunch of garbage errors.

Would you mind updating this to master yourself when you have time?

**Comment by EtienneBruines** [comment]
@matiwinnetou how does this work for you?

**Comment by paked** [comment]
LGTM.

**Pull request merged**
