### PR TITLE
Fixed audio on Windows

### LINKED ISSUE #140: package issues on windows
Hey guys
I'm trying to test the engine
I'm getting this issue when getting the source

```go
 go get -u github.com/paked/engi
package golang.org/x/mobile/exp/audio/al: no buildable Go source files in C:\media\PROJECTx\mixgo\src\golang.org\x\mobile\exp\audio\al
```

I'm new to Go so not sure what the issue is, I'm using windows 10 64bit

thanks

### PR DESCRIPTION
**Pull request by EtienneBruines**
Should fix #140.

Could you check if this fixes the problem, @varomix?

### CODE REVIEW

**Comment by varomix** [comment]
Hi Etienne
I just tried it but I still get the same error

```go
 go get -u github.com/paked/engi
package golang.org/x/mobile/exp/audio/al: no buildable Go source files in C:\media\PROJECTx\mixgo\src\golang.org\x\mobile\exp\audio\al
```

Should I clean up the folder first or something?

thanks for the help

**Comment by paked** [comment]
@varomix Try again now, I hadn't merged the PR into master :smile:.

**Comment by varomix** [comment]
@paked I tried again I still get the same error
I tried deleting everything and still same result
```
$ go get -u github.com/paked/engi
package golang.org/x/mobile/exp/audio/al: no buildable Go source files in C:\media\PROJECTx\mixgo\src\golang.org\x\mobile\exp\audio\al
```

Last night I read that this might be a windows issue with the audio it might not work for windows yet
this might have something to do
https://github.com/golang/go/issues/12261

thanks

**Comment by varomix** [comment]
Any of you have it working on windows?
I'll switch to linux but the issue will still be there :)

**Comment by paked** [comment]
@varomix The problem doesn't actually doesn't exist on OSX/Linux, it was caused by the `golang.org/x/mobile/exp/audio/al` not supporting Windows straight up. Now that I've merged this pull request in it should no longer be an issue.

**Comment by varomix** [comment]
ok so I installed on my desktop computer on windows as well to see if it was some kind of issue on my laptop, I got another error and the previous one as well

```
$ go get -u github.com/paked/engi
package golang.org/x/image/math/f32: unrecognized import path "golang.org/x/image/math/f32"
package golang.org/x/mobile/exp/audio/al: no buildable Go source files in C:\gowork\src\golang.org\x\mobile\exp\audio\al
```

I just did this on a fresh windows computer with no previous Go stuff on it
so I guess the issue is still there.

This is on windows 8.1 64 bit

Thanks

**Comment by paked** [comment]
@EtienneBruines I don't have access to a Windows PC currently, so it looks like you're going to have to take this.

**Comment by gelidus** [comment]
Getting this error while go getting the engi. Also cant compile anything:
```
package golang.org/x/mobile/exp/audio/al: no buildable Go source files in C:\gospace\src\golang.org\x\mobile\exp\audio\al
```

**Pull request merged**
