### PR TITLE
Fixes for AnimationComponent and AnimationSystem

### PR DESCRIPTION
**Pull request by matiwinnetou**

### CODE REVIEW

**Comment by matiwinnetou** [comment]
This fixed #4 as far as I am concerned. Please review. I think there may be bugs especially with Cam since I understand the least about this.

@EtienneBruines @paked review please.

**Comment by EtienneBruines** [comment]
This does look quite amazing. (have yet to try the demo)

**Comment by EtienneBruines** [comment]
LGTM - this demo looks nice. 

But it has more code than I can see results of? I only see him walking. (starting IRC)

**Comment by paked** [comment]
Everything LGTM. Is this ready for merge @matiwinnetou?

**Comment by matiwinnetou** [comment]
Yes, merge please. If fine with you.

**Comment by paked** [comment]
Thanks for the contribution @matiwinnetou!

**Pull request merged**
