### PR TITLE
Updated the Camera API

### PR DESCRIPTION
**Pull request by EtienneBruines**
## Camera API
Objects are now positioned/drawn where they should be. The
`glfw` part worries about where the camera is, and where the
objects should be rendered.

Added some tests to ensure its behavior doesn't change over time.

Removed the `Clamp` function in the math file, because it's
probably better to use the `mgl32` package for things like that. No
need to define it twice.

Renamed the `gl` variable in engi, because having both `gl` and `Gl`,
referencing to the exact same object, doesn't make any sense.

## KeyboardScroller
I also added a `KeyboardScroller`. It's a `Systemer` people can add using 
```go
game.AddSystem(engi.NewKeyboardScroller(scrollSpeed, engi.W, engi.D, engi.S, engi.A))
```
And then everything works out-of-the-box. No need to create a separate `Entity` for it. 

## EdgeScroller
Much like the `KeyboardScroller`, we now have a `EdgeScroller` which everyone can use:
```go
game.AddSystem(engi.NewEdgeScroller(scrollSpeed, edgeMargin))
```
Then all you need to do, is move your cursor to the edge of the window, to scroll :-).

### CODE REVIEW

**Comment by paked** [comment]
Is there any chance we could get an example of each `*Scroller` in the `demos` folder? Apart from that, LGTM.

**Comment by EtienneBruines** [comment]
One demo for each, or one demo that includes both?

**Comment by paked** [comment]
@EtienneBruines one demo for each

**Comment by EtienneBruines** [comment]
Will have it ready some time tomorrow evening (so that'll be Saturday for you ;-) ).

**Comment by paked** [comment]
@EtienneBruines Awesome. Thanks for the contribution, its really awesome!

**Comment by matiwinnetou** [comment]
awesome stuff :+1:

**Comment by EtienneBruines** [comment]
@paked I had some time to kill, so here are two demos. 

As you'll see in the demos, the `Camera` behavior isn't perfect just yet (it doesn't let you zoom down all the way).

**Comment by paked** [comment]
@EtienneBruines pinged you on slack... Having troubles getting this to compile:

```
# github.com/paked/engi
../../batch.go:117: Gl.Uniform3f undefined (type *webgl.Context has no field or method Uniform3f)
```

**Comment by EtienneBruines** [comment]
My bad. https://github.com/paked/webgl/pull/1

**Comment by paked** [comment]
@EtienneBruines I'd really like to get the padding issues fixed up before merging this in. Do you have the bandwidth for this, or should I merge in and investigate myself?

**Comment by paked** [comment]
Actually it looks like this may not be a problem in the `Camera` API

**Comment by EtienneBruines** [comment]
Most-likely not in `camera.go`, but the code that's listed in `assets.go` and `batch.go` is certainly involved. 

(I see my response went missing; I said that I've got no idea how to fix the problem; has something to do with that Shader code (C) )

**Comment by paked** [comment]
@EtienneBruines I'll take a look later today.

Thanks for the contribution!
taking_content

**Pull request merged**
