### PR TITLE
Tuned Performance

### PR DESCRIPTION
**Pull request by EtienneBruines**
### CollisionSystem
Performance increased about `10-15%`.

### Component
Performance increased about `20-25%`. 

(I know the branch has an incorrect name ;-) )

### CODE REVIEW

**Comment by paked** [comment]
This LGTM.

**Comment by paked** [comment]
This doesn't depend on any changes from #50 does it?

**Comment by EtienneBruines** [comment]
No, it does not. 

I did use #50 to come up with the performance measurements, but these changes are separate.

**Comment by EtienneBruines** [comment]
Merging because of the `LGTM` - and this way I can also change the other PRs to reflect changes.

**Comment by paked** [comment]
Good call.

**Pull request merged**
