### PR TITLE
Implemented PauseSystem and updated Message

### PR DESCRIPTION
**Pull request by EtienneBruines**
**[BREAKING CHANGE]**
`MessageManager.Dispatch` now only requires the `Message`, no `Name` `string`.
This is because this information is already in `Message.Type()`

`Handler` now is no longer `func(i interface{})`, but `func(msg Message)`,
since we know it'll be a message - it's best to use type safety.
It's also renamed to `MessageHandler`, to be more specific.

Fixed the examples so it didn't break anything.

Added demo for the `PauseSystem`. Should go a long way with #27.

### CODE REVIEW

**Comment by paked** [comment]
LGTM once we have established this is the messaging model we want to use

cc: @EtienneBruines @matiwinnetou

**Comment by EtienneBruines** [comment]
w.r.t. the `PauseSystem`, or in general?

**Comment by paked** [comment]
@EtienneBruines In general. I personally think this is the best model...

**Comment by EtienneBruines** [comment]
Removed the log/debug message. Some TODOs can't change until #35 is fixed.

**Comment by EtienneBruines** [comment]
Gotta say. Trying to refactor `Responder` has made me think about the design.

There's a separate `PauseSystem`, to which a message will be sent. This system then, alters the `World`. 

The only things that can send such `Message` to the `PauseSystem`, are other `System`s. Why don't we let them directly manipulate the `World`? It'll still be a `System` that modifies the `World`.

**Comment by paked** [comment]
@EtienneBruines This seems interesting, although I'm not quite sure I understand what you are saying

**Comment by EtienneBruines** [comment]
Why are we requiring the user-made `System`, to send a `Message` to our `PauseSystem`, such that our `PauseSystem` can alter the `World` (pause it), 

when that user-made `System` could alter the `World` (pause it) itself, directly?

**Comment by paked** [comment]
@EtienneBruines that makes sense. So you're saying we make pausing behaviour a first class citizen?

**Comment by EtienneBruines** [comment]
Wouldn't hurt. The only difference between that, and the current implementation:
* Now `World` has a unexported variable `isPaused`;
* Now `PauseSystem` can alter that value directly, when it receives a message;
* Then, a simple `World.Pause()` function would suffice - no need for messages. 

Since it's directly *changing the world*, if it's a system, it shouldn't matter if we programmed the system, or if they did?

**Comment by paked** [comment]
I think perhaps it is better design for us to "eat our own dog food" and build internal Systems following the pattern we expect others too.

**Comment by EtienneBruines** [comment]
So, remove `PauseSystem`, and create some kind of `Pause` function on `World`?

**Comment by paked** [comment]
No. Build a `PauseSystem` for others to use, which makes use of a private function `pause()` on `World`.

**Comment by EtienneBruines** [comment]
Roger that. Then I believe this PR does exactly that. (perhaps not a private `pause()` function, but alters the `isPaused` variable).

**Comment by matiwinnetou** [comment]
I would agree with @paked but maybe over time I may change my mind. Now I think we should really use ECS where we can but maybe over time we will find which things work, which don't.

**Comment by paked** [comment]
OK LGTM then.

**Pull request merged**
